spring.datasource.url=jdbc:mysql://localhost:3306/freshmapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=pvtapp
server.port=8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB


storage.local.path=uploads

# JWT Configuration
jwt.secret=6B6F1C4E5A7D9F2B8C3E6A9D1F7B5C8E4A2D9F6C1B7E3A5D8F4C9E2A6B1D7F5
jwt.expiration=86400000