spring.datasource.url=jdbc:mysql://localhost:3306/freshmapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=freshm
spring.datasource.password=freshm123

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=true

spring.application.name=pvtapp
server.port=8083

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

# JWT Configuration
jwt.secret=6B6F1C4E5A7D9F2B8C3E6A9D1F7B5C8E4A2D9F6C1B7E3A5D8F4C9E2A6B1D7F5
jwt.expiration=86400000


spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

file.upload-dir=uploads
storage.local.path=uploads

spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false
